WHITESPACE = _{ " " | NEWLINE }

program = { SOI ~ statement* ~ EOI }

    statement = { assignment | expression_statement }
        assignment = { identifier ~ "=" ~ expression ~ ";" }
        expression_statement = { expression ~ ";" }

    identifier = { ASCII_ALPHA_LOWER ~ ASCII_ALPHA* }
    expression = { term ~ (">>" ~ term)* }
        term = { atom ~ (call | index | range)* }
            atom = { integer_literal | negative_integer | string_literal | identifier | array }
                negative_integer = { "-" ~ integer_literal }
                integer_literal = { ASCII_DIGIT+ }
                string_literal = { "'" ~ (!"'" ~ ANY)* ~ "'"}
                array = { "[" ~ (expression ~ ("," ~ expression)*)? ~ "]"}
            // For now, we only allow single-argumment function calls
            call = { "(" ~ expression ~ ("," ~ expression)* ~ ")" }
            index = { "[" ~ expression ~ "]" }
            range = { "[" ~ range_start? ~ ":" ~ range_end? ~ (":" ~ range_step)? ~ "]" }
                range_start = { expression }
                range_end = { expression }
                range_step = { expression }
