WHITESPACE = _{ " " | NEWLINE }

program = { SOI ~ statement* ~ EOI }

    statement = { assignment | expression_statement }
        assignment = { identifier ~ "=" ~ expression ~ ";" }
        expression_statement = { expression ~ ";" }

    identifier = { ASCII_ALPHA_LOWER ~ ASCII_ALPHA* }
    expression = { term ~ (">>" ~ term)* }
        term = { atom ~ (call | index)* }
            atom = { integer_literal | string_literal | identifier | array }
                integer_literal = { ASCII_DIGIT+ }
                string_literal = { "'" ~ (!"'" ~ ANY)* ~ "'"}
                array = { "[" ~ (expression ~ ("," ~ expression)*)? ~ "]"}
            // For now, we only allow single-argumment function calls
            call = { "(" ~ expression ~ ("," ~ expression)* ~ ")" }
            index = { "[" ~ expression ~ "]" }
